DEFAULT_OPENRESTY_VERSION=1.31.1.1
OPENRESTY_VERSION=${OPENRESTY_VERSION:-${DEFAULT_OPENRESTY_VERSION}}
OPENRESTY_FALLBACK_VERSION=${OPENRESTY_FALLBACK_VERSION:-${DEFAULT_OPENRESTY_VERSION}}
ALLOW_LATEST_FALLBACK=${ALLOW_LATEST_FALLBACK:-true}
