OPENRESTY_VERSION=1.31.1.1
OPENSSL_VERSION=3.5.6
OPENSSL_PATCH_VERSION=3.5.5
PCRE2_VERSION=10.47
ENABLE_PCRE2=true
USE_GCC_WRAPPER=true
SUB_FILTER_VERSION=e12e965ac1837ca709709f9a26f572a54d83430e
ENABLE_SUBSTITUTIONS_FILTER=true
ENABLE_UPSTREAM_CHECK=false
