upstream app_backend {
    server 192.168.1.101:8080;
    server 192.168.1.102:8080;
    check interval=3000 rise=2 fall=3 timeout=1000 type=http;
    check_http_send "GET /health HTTP/1.0\r\nHost: localhost\r\nConnection: close\r\n\r\n";
    check_http_expect_alive http_2xx http_3xx;
}
server {
    listen 127.0.0.1:8088;
    location = /nginx_status {
        stub_status;
        access_log off;
    }
    location = /upstream_status {
        check_status json;
        access_log off;
    }
}
